services:

  # Database image
  postgres_app:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: always

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  # Application image
  app:
    build: .
    container_name: contas-service
    ports:
      - "8080:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_app:5432/appdb
      SPRING_DATASOURCE_URL_FLYWAY:
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppassword

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_SHOW_SQL: "false"

      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres_app:5432/appdb
      SPRING_FLYWAY_USER: appuser
      SPRING_FLYWAY_PASSWORD: apppassword

      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - app-network
    depends_on:
      postgres_app:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge